### ISSUE TITLE
MSYS2...

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/virtual-environments#1]
@m-minasyan

Sorry for the ping, but I noticed some branches in your fork...

1. In the header for [`Install-MSYS2.ps1`](https://github.com/m-minasyan/virtual-environments/blob/v-mimina/msys2-install-for-test-2/images/win/scripts/Installers/Install-MSYS2.ps1#L2-L3), I left the phrase '(32-bit commented out)'.  At a later time, I uncommented the code to install 32 bit tools.  Depending on what's decided as to including 32 build tools, that could/should be deleted.

2. Re `Validate-MSYS2.ps1`, please consider adding a test for `pacman`.  If that doesn't work...  **EDIT:** Disregrard.  The install will fail if `pacman` doesn't work...

3. MSYS2 and system PATH - quite a mess.  When using 64 bit tools, path changes are a combination of `C:\msys64\mingw64\bin`, `C:\msys64\clang64\bin`, and `C:\msys64\usr\bin`, 32 bit tools are `C:\msys64\mingw32\bin`, `C:\msys64\clang32\bin`, and `C:\msys64\usr\bin`.  I would suggest leaving MSYS2 out of the system path and letting people change it in their scripts/workflows.  If people reach as consensus as to adding some or all to the system PATH, it can be changed later.  There's already a lot of conflicts on Windows images.

Thanks for your work on this, Greg

**Comment by m-minasyan** [comment]
Thank you @MSP-Greg, I do as you suggest.

**Comment by MSP-Greg** [comment]
@m-minasyan

Sorry for the 2nd ping, but the script I had in the PR was a 'draft', and I wasn't sure whether anything would happen.  I double checked things, and one more change might be a good idea.

In [`Install-MSYS2.ps1`](https://github.com/m-minasyan/virtual-environments/blob/v-mimina/msys2-install-for-test-2/images/win/scripts/Installers/Install-MSYS2.ps1#L44-L45) are the following two lines:
```ps1
Write-Host "pacman --noconfirm -Syyuu"
pacman.exe -Syyuu --noconfirm
```

Based on an MSYS2 repo that actually packages a 'nightly' MSYS2 install file, maybe change to the following, based on MSYS2 pipelines code [here](https://github.com/msys2/msys2-installer/blob/master/azure-pipelines.yml#L31-L32):
```ps1
# https://github.com/msys2/msys2-installer/blob/master/azure-pipelines.yml
# see 'Update MSYS2' step
Write-Host "pacman --noconfirm -Syyuu"
pacman.exe --noconfirm -Syyuu
Write-Host "pacman --noconfirm -Syuu"
pacman.exe --noconfirm -Syuu
```

Thanks.  I've now reviewed everything...

**Comment by m-minasyan** [comment]
@MSP-Greg Ok, thanks.
